//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhoHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int maCTHD { get; set; }
        public int maSP { get; set; }
        public int maMH { get; set; }
        public int maHD { get; set; }
        public int giaTien { get; set; }
        public int soLuong { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual MatHang MatHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
